datasource:
  schema: 'db'
  host: '${dockerdbhost:localhost}:3307'
  url: 'jdbc:mysql://${datasource.host}/${datasource.schema}'
  username: 'user'
  password: 'password'
spring:
  datasource:
    name: 'MyPetDataSource'
    url: '${datasource.url}'
    username: '${datasource.username}'
    password: '${datasource.password}'
    initialization-mode: always

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none